# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [2]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /tmp/build-env-8744k94k/bin/python
  version: '3.12'
SIMD Extensions:
  baseline:
  - SSE
  - SSE2
  - SSE3
  found:
  - SSSE3
  - SSE41
  - POPCNT
  - SSE42
  - AVX
  - F16C
  - FMA3
  - AVX2
  not found:
  - AVX512F
  - AVX512CD
  - AVX512_KNL
  - AVX512_KNM
  - AVX512_SKX
  - AVX512_CLX
  - AVX512_CNL
  - AVX512_ICL

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [4]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [5]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [6]:
v = np.arange(10)
print(v[::-1])

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [9]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [10]:
v = np.array([1,2,0,0,4,0])
print(np.nonzero(v))

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [12]:
# identity matrix: 항등 행렬
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [27]:
print(np.random.random((3,3,3)))

[[[0.94305582 0.41909342 0.25863397]
  [0.95674857 0.08392405 0.07242327]
  [0.08031342 0.65417675 0.74149011]]

 [[0.76550289 0.82613274 0.63990073]
  [0.81579684 0.09337234 0.67710688]
  [0.34674628 0.12554177 0.73851765]]

 [[0.9931929  0.48685269 0.29078446]
  [0.03153997 0.7841356  0.19581824]
  [0.87461205 0.87572174 0.36586548]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [26]:
v = np.random.random((10,10))
print(v.min(), v.max())

0.01719472799515176 0.9898546005644365

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [19]:
v = np.random.random(30)
print(v.mean())

0.5417763684894041

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [29]:
v = np.ones((10,10))
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [34]:
v = np.ones((5,5))
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [35]:
v[[0,-1], :] = 0
v[:, [0,-1]] = 0
print(v)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
print(0 * np.nan) # 어떤 숫자와 nan을 곱하면 nan
print(np.nan == np.nan) # nan은 자기 자신과 비교해도 같지 않음
print(np.inf > np.nan) # nan은 다른 값과 비교할 수 없음
print(np.nan - np.nan) # nan에서 nan을 빼도 nan
print(np.nan in set([np.nan])) # set 내에서는 nan이 동등하게 취급되어 포함 여부 확인 가능
print(0.3 == 3 * 0.1) # 부동소수점 연산의 정밀도 문제로 두 값이 다를 수 있음

nan
False
False
nan
True
False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [45]:
# 정규화 과정
v = np.random.random((5,5))
# 정규화 공식 이용
print((v-v.mean()) - v.std()) # std(): 표준편차

[[-0.65708304 -0.60090838  0.06816227 -0.40794323 -0.12940248]
 [-0.65497097 -0.57718765 -0.09188103  0.15873066 -0.66471478]
 [ 0.03452788 -0.78745254  0.11694796 -0.10337993 -0.7069341 ]
 [-0.43525155 -0.35210793 -0.11213928 -0.53549447 -0.56782361]
 [-0.01494062 -0.45379328  0.15607149 -0.41559217  0.06461441]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [46]:
# 행렬 내적 dot()
np.ones((5,3))
np.ones((3,2))
print(np.dot(np.ones((5,3)), np.ones((3,2))))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
print(np.array(0) / np.array(0)) # 0을 0으로 나누는 연산은 수학적으로 정의 불가
print(np.array(0) // np.array(0)) # 0을 0으로 나눈 몫은 부정의 값이며 numpy는 이 결과를 0으로 간주
print(np.array([np.nan]).astype(int).astype(float)) # np.nan을 정수형으로 변환하려고 할 때 유효하지 않은 값으로 간주 후 표현 가능한 가장 작은 값으로 반환

nan
0
[-9.22337204e+18]

/tmp/ipykernel_1141/3504765454.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) # 0을 0으로 나누는 연산은 수학적으로 정의 불가
/tmp/ipykernel_1141/3504765454.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # 0을 0으로 나눈 몫은 부정의 값이며 numpy는 이 결과를 0으로 간주
/tmp/ipykernel_1141/3504765454.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) # np.nan을 정수형으로 변환하려고 할 때 유효하지 않은 값으로 간주 후 표현 가능한 가장 작은 값으로 반환

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [53]:
v = np.zeros((5,5))
v += np.arange(5) # 반복문 안 돌려도 행 전체에 더해짐 (넘파이 브로드캐스팅)
print(v)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [60]:
v = np.random.random(10)
v.sort()
print(v)

[0.18085235 0.29478424 0.34107309 0.35095911 0.4105199  0.42780236
 0.532437   0.60727256 0.64550756 0.83033603]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [61]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [62]:
print(pd.__version__)

2.2.2

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [68]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [71]:
df.info() # 데이터의 구조적인 정보 제공

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [72]:
df.describe() # 데이터에 대한 통계적 요약 제공

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [73]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [74]:
print(df[['animal', 'age']]) # column 인덱싱

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [75]:
print(df.loc[['d','e','i'], ['animal','age']]) # column & row 인덱싱 with loc()

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [76]:
print(df[df['visits'] > 3]) # boolean 인덱싱

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [79]:
print(df[df['age'].isnull()]) # boolean 인덱싱 응용

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [82]:
print(df[(df['animal'] == 'cat') & (df['age'] < 3)]) # boolean 인덱싱 응용

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [84]:
print(df[df['age'].between(2,4)]) # between() 메서드 이용한 특정 범위 내에 있는 값 선택

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [85]:
df.loc['f', 'age'] = 1.5
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [86]:
print(df['visits'].sum())

19

### 15. Calculate the mean age for each different animal in `df`.

In [89]:
print(df.groupby('animal')['age'].mean()) # groupby() 메서드 이용한 column 그룹화 응용

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [91]:
df.loc['k'] = ['dog', 5.5, 2, 'no']
print(df, '\n')

df = df.drop('k')
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  5.5       2       no

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [94]:
print(df['animal'].value_counts()) # 복잡한 분석이 아닌 경우 groupby() 사용 X

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [96]:
print(df.sort_values(by=['age','visits'], ascending=[False,True])) # sort 우선순위: 1.age 2.visits

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [98]:
df['priority'] = df['priority'].map({'yes':True, 'no':False}) # map() 이용한 값 치환
print(df)

  animal  age  visits priority
a    cat  2.5       1      NaN
b    cat  3.0       3      NaN
c  snake  0.5       2      NaN
d    dog  NaN       3      NaN
e    dog  5.0       2      NaN
f    cat  1.5       3      NaN
g  snake  4.5       1      NaN
h    cat  NaN       1      NaN
i    dog  7.0       2      NaN
j    dog  3.0       1      NaN

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [99]:
df['animal'] = df['animal'].replace('snake','python') # replace() 이용한 특정 값 치환
print(df)

   animal  age  visits priority
a     cat  2.5       1      NaN
b     cat  3.0       3      NaN
c  python  0.5       2      NaN
d     dog  NaN       3      NaN
e     dog  5.0       2      NaN
f     cat  1.5       3      NaN
g  python  4.5       1      NaN
h     cat  NaN       1      NaN
i     dog  7.0       2      NaN
j     dog  3.0       1      NaN

In [100]:
# 확인용 df 출력 셀
df

   animal  age  visits priority
a     cat  2.5       1      NaN
b     cat  3.0       3      NaN
c  python  0.5       2      NaN
d     dog  NaN       3      NaN
e     dog  5.0       2      NaN
f     cat  1.5       3      NaN
g  python  4.5       1      NaN
h     cat  NaN       1      NaN
i     dog  7.0       2      NaN
j     dog  3.0       1      NaN

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [102]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
print(df, '\n')
df = df.sub(df.mean(axis=1), axis=0) # axis=0: row, axis=1: column
print(df) # 마찬가지로 pandas의 브로드캐스팅으로 인해 반복문 사용 안 해도 OK

          0         1         2
0  0.135488  0.887852  0.932606
1  0.445568  0.388236  0.257596
2  0.657368  0.492617  0.964238
3  0.800984  0.455205  0.801058
4  0.041718  0.769458  0.003171

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278

In [105]:
# 각 행의 평균을 df.mean(axis=1)로 계산 후 df.sub()로 감싸 계산했습니다.