# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [3]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [3]:
print(np.__version__)

1.26.4

In [5]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/0315j/anaconda3/Library/include
    lib directory: C:/Users/0315j/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\python.exe
  version: '3.12'
SIMD Extensions:
  baseline:
  - SSE
  - SSE2
  - SSE3
  found:
  - SSSE3
  - SSE41
  - POPCNT
  - SSE42
  - AVX
  - F16C
  - FMA3
  - AVX2
  not found:
  - AVX512F
  - AVX512CD
  - AVX512_SKX
  - AVX512_CLX
  - AVX512_CNL
  - AVX512_ICL

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [13]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [15]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [25]:
np.arange(9, -1,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [35]:
# 인덱스
vector = np.array([1, 2, 0, 0, 4, 0])
vector[[3, 0, 4]]

array([0, 1, 4])

In [37]:
# 튜플
vector = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(vector)

(array([0, 1, 4], dtype=int64),)

In [39]:
vector = np.array([1, 2, 0, 0, 4, 0])
i = np.nonzero(vector)
i

(array([0, 1, 4], dtype=int64),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [43]:
a = np.zeros((3,3))
a[[0,1,2],[0,1,2]] = 1
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [49]:
np.random.rand(3, 3)

array([[0.87196795, 0.73555217, 0.08879177],
       [0.35714316, 0.63529772, 0.68061636],
       [0.90642497, 0.86640795, 0.48674965]])

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [63]:
a = np.random.rand(10, 10)
a

array([[0.59111492, 0.57603335, 0.96553515, 0.9273121 , 0.37587759,
        0.38936851, 0.55825347, 0.23920728, 0.82020931, 0.44015468],
       [0.29173451, 0.27372878, 0.502514  , 0.61461591, 0.618025  ,
        0.74791234, 0.80433749, 0.9826939 , 0.56042897, 0.98094731],
       [0.31585783, 0.40169019, 0.36690505, 0.73881981, 0.28987593,
        0.08939314, 0.79906719, 0.53223996, 0.39633042, 0.65028924],
       [0.93730319, 0.96742228, 0.14570121, 0.74622604, 0.93186681,
        0.98765115, 0.68022866, 0.10947662, 0.35712246, 0.93749443],
       [0.93536481, 0.60647532, 0.05360182, 0.43761337, 0.815698  ,
        0.54775425, 0.44257068, 0.12322256, 0.85205782, 0.07933766],
       [0.53340418, 0.27121296, 0.30501866, 0.6241989 , 0.48209146,
        0.77233027, 0.52926276, 0.61056253, 0.27161676, 0.24056147],
       [0.26267632, 0.71430508, 0.81971453, 0.53986985, 0.58389031,
        0.66721329, 0.36401426, 0.64929154, 0.74617965, 0.79715607],
       [0.65689826, 0.59036144, 0.00630232, 0.2489007 , 0.81310242,
        0.60372095, 0.14410271, 0.29186836, 0.88716994, 0.08890757],
       [0.41010513, 0.25416383, 0.35024218, 0.46113274, 0.45346828,
        0.75497675, 0.94077059, 0.04931169, 0.43550129, 0.99889989],
       [0.81227842, 0.8628892 , 0.74524037, 0.38783255, 0.15949276,
        0.95121075, 0.18954277, 0.14741846, 0.97249792, 0.27119198]])

In [65]:
min_val = a.min()
max_val = a.max()

print(min_val, max_val)

0.006302321823105306 0.9988998942463453

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [67]:
a = np.random.rand(30,)
a.mean()

0.46846674341444683

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [71]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0

In [77]:
a = np.zeros((10, 10))
a[0, :] = 1     
a[-1, :] = 1    
a[:, 0] = 1       
a[:, -1] = 1 
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [83]:
a = np.ones((5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
a[0, :] = 0     
a[-1, :] = 0
a[:, 0] = 0     
a[:, -1] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [5]:
0 * np.nan

nan

nan는 아무런 숫자가 없다는 뜻이기에 0과 곱해도 아무런 연산이 이루어지지 않는다.

In [12]:
np.nan == np.nan

False

nan는 아무런 숫자가 아니기에 연립이 성립되지 않는다.

In [14]:
np.inf > np.nan

False

nan는 아무런 숫자가 아니기에 연립이 성립되지 않는다.

In [20]:
np.nan - np.nan

nan

nan는 아무런 숫자가 아니기에 연산이 이루어지지 않는다.

In [22]:
np.nan in set([np.nan])

True

?

In [25]:
0.3 == 3 * 0.1

False

!! 0.1은 이진수로 표현 불가능
실제론 0.1 ≈ 0.10000000000000000555...
0.3 =/= 0.30000000000000004 이기에 False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [37]:
a = np.random.rand(5, 5)

In [39]:
a

array([[0.47670039, 0.02375982, 0.84325238, 0.48454604, 0.4650187 ],
       [0.69748794, 0.33645459, 0.34426425, 0.05444177, 0.99727358],
       [0.94775601, 0.76303812, 0.54627962, 0.92228471, 0.66328174],
       [0.48464394, 0.31835435, 0.98588255, 0.97265526, 0.45736761],
       [0.4283267 , 0.81273061, 0.57096234, 0.93875303, 0.57814568]])

In [41]:
(a - a.mean())/a.std()

array([[-0.46532789, -2.11391878,  0.8688301 , -0.4367717 , -0.50784635],
       [ 0.3382838 , -0.97578768, -0.94736248, -2.00224412,  1.4294289 ],
       [ 1.24919726,  0.57687013, -0.21207681,  1.1564881 ,  0.21378176],
       [-0.43641535, -1.04166804,  1.38796838,  1.33982433, -0.53569439],
       [-0.64139609,  0.75773843, -0.12223788,  1.21642867, -0.09609231]])

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [51]:
a = np.ones((5,3))
b = np.ones((3,2))

np.dot(a,b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [53]:
np.array(0) / np.array(0)

C:\Users\0315j\AppData\Local\Temp\ipykernel_17120\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)

nan

In [ ]:
0은 분모에 갈 수 없기에

In [55]:
np.array(0) // np.array(0)

C:\Users\0315j\AppData\Local\Temp\ipykernel_17120\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)

0

In [ ]:
!! 경고가 발생하나 결과 값은 0

In [57]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\0315j\AppData\Local\Temp\ipykernel_17120\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [ ]:
!! nan는 정수로 표현이 불가능하기에 int형에선 int 중 가장 작은 수 -> float이 되면서 그대로 출력

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [63]:
np.ones((5,1)) * np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [65]:
np.arange(5).reshape(1,5).repeat(5, axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [73]:
a = np.random.rand(10,)
a

array([0.84854594, 0.40290832, 0.8620341 , 0.22386986, 0.2583278 ,
       0.39585514, 0.94953127, 0.63383197, 0.74522522, 0.77167022])

In [77]:
b = np.sort(a)
b

array([0.22386986, 0.2583278 , 0.39585514, 0.40290832, 0.63383197,
       0.74522522, 0.77167022, 0.84854594, 0.8620341 , 0.94953127])

## **판다스**


### 1. Import pandas under the alias `pd`.

In [79]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [81]:
print(pd.__version__)

2.2.3

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [83]:
# 문제 풀이 전 numpy 임포트
import numpy as np

In [85]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

In [87]:
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [95]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [91]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [97]:
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [103]:
df.iloc[[3,4,8]][['animal','age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [109]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [101]:
df.isna()

   animal    age  visits  priority
a   False  False   False     False
b   False  False   False     False
c   False  False   False     False
d   False   True   False     False
e   False  False   False     False
f   False  False   False     False
g   False  False   False     False
h   False   True   False     False
i   False  False   False     False
j   False  False   False     False

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [119]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [121]:
df[(df['age'] >= 2) & (df['age'] <= 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [125]:
df.loc['f', 'age'] = 1.5

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [129]:
df['visits'].sum()

19

### 15. Calculate the mean age for each different animal in `df`.

In [131]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [139]:
df.loc['k'] = ['cat', 5, 3, 'yes']
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.0       3      yes

In [141]:
df = df.drop('k')
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [145]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [153]:
df.sort_values(by=['age','visits'], ascending=[False, True])

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [158]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [164]:
df['animal'] = df['animal'].replace('snake','python')

In [166]:
# 확인용 df 출력 셀
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [171]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

In [173]:
df

          0         1         2
0  0.135488  0.887852  0.932606
1  0.445568  0.388236  0.257596
2  0.657368  0.492617  0.964238
3  0.800984  0.455205  0.801058
4  0.041718  0.769458  0.003171

In [175]:
df.sub(df.mean(axis=1), axis=0)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278

In [ ]:
15-5, 19번