In [1]:
import numpy as np

In [2]:
#2
print (np.__version__)
print(np.show_config)

2.0.2
<function show at 0x7c12ae99eb60>

In [3]:
#3
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [4]:
#4
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

In [5]:
#5
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [6]:
#6
vector = np.arange(10)
Reverse_vector = np.sort(vector)[::-1]
print(Reverse_vector)

[9 8 7 6 5 4 3 2 1 0]

In [7]:
#7
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [8]:
#8
array1= np.array([1,2,0,0,4,0])
indices = np.array ([0,1,2,3,4,5])
non_zero = indices[array1 > 0]
print((non_zero,))

(array([0, 1, 4]),)

In [9]:
#9
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [10]:
#10
matrix = np.random.random((3, 3, 3))
print(matrix)

[[[0.26178375 0.12700323 0.42221133]
  [0.28063111 0.57665231 0.58773154]
  [0.9384368  0.29311103 0.11381247]]

 [[0.96526994 0.38556183 0.38849662]
  [0.56574225 0.61330331 0.3602045 ]
  [0.70227295 0.18322384 0.25526388]]

 [[0.41468959 0.80654652 0.75880568]
  [0.45833845 0.3932291  0.39751999]
  [0.58437367 0.02195069 0.21357779]]]

In [11]:
#11
matrix = np.random.random((10, 10))
Max = matrix.max()
Min = matrix.min()
print(Max, Min)

0.9882675776012383 0.002312633000373654

In [12]:
#12
vector = np.random.random(30)
Mean = vector.mean()
print(Mean)

0.5218475071089312

In [13]:
#13
array1 = np.ones((10, 10))
array1[1:-1, 1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [14]:
#14
array1 = np.ones((5, 5))
print("# before \n", array1)
array1[:,[0,4]] = 0
array1[[0,4],:] = 0
print("# after \n", array1)

# before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

In [15]:
#15
0 * np.nan
# nan은 정의되지 않은 값이기에 0을 곱해도 정의되지 않음

nan

In [16]:
np.nan == np.nan
# nan은 정의되지 않은 값이기에 nan 자기자신과도 같다고 할 수 없음

False

In [17]:
np.inf > np.nan
# nan은 정의되지 않은 값이기에 무한대와도 비교할 수 없음

False

In [18]:
np.nan - np.nan
# 정의되지 않은 숫자끼리 계산된 값 역시 정의되지 않음

nan

In [19]:
np.nan in set([np.nan])
# 집합은 주소를 확인하여 같은 것으로 처리

True

In [20]:
0.3 == 3 * 0.1
# 컴퓨터가 이진수로 계산하는 과정에서 발생한 반올림오차에 의해 달라짐

False

In [21]:
#16
matrix = np.random.random((5,5))
normal = (matrix - matrix.mean()) / matrix.std()
print(normal)

[[ 0.17811594  0.29279068 -0.01708525  0.76915279  1.0769836 ]
 [-0.9305726   1.07231886  0.74496418 -1.15452188  1.33765495]
 [-0.71131641 -0.86445357  1.52335913  1.56756482  0.20075453]
 [-0.66684185  0.91956003 -0.89400747 -0.08219637 -1.01998723]
 [ 1.52131203 -1.20392734 -1.25178501 -1.2045548  -1.20328176]]

In [22]:
#17
A = np.ones((5, 3))
B = np.ones((3, 2))
Multi = np.dot(A, B)
print(Multi)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

In [26]:
#18
np.array(0) / np.array(0)
# 0을 0으로 나누는 것은 정의될 수 없어 nan이 반환됨

/tmp/ipykernel_255/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)

np.float64(nan)

In [24]:
np.array(0) // np.array(0)
# 위와 같은 이유

/tmp/ipykernel_255/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)

np.int64(0)

In [25]:
np.array([np.nan]).astype(int).astype(float)
# nan을 정수로 변환하면 표현할 수 없는 값이라 최솟값으로 변환됨.
# 다시 실수형으로 바꾸면 해당 값이 지수 표기법으로 표현됨.

/tmp/ipykernel_255/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [27]:
#19
ones = np.ones((5, 1))
row = np.arange(5)
matrix = ones * row
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [28]:
#20
vector1 = np.random.random(10)
vector1.sort()
print(vector1)

[0.0314252  0.047821   0.31318792 0.35430964 0.4076593  0.43157962
 0.52234546 0.64503192 0.6842788  0.71135965]

In [29]:
import pandas as pd

In [30]:
#2
print(pd.__version__)

2.2.2

In [31]:
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [34]:
#3
df = pd.DataFrame(data, index=labels)

In [35]:
#4
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

In [36]:
#5
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [37]:
#6
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [38]:
#7
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [39]:
#8
df.iloc[[3, 4, 8]][['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [42]:
#9
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [43]:
#10
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [44]:
#11
df[(df['animal'] == 'cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [45]:
#12
df[(df['age'] >= 2) & (df['age'] <= 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [46]:
#13
df.loc['f', 'age'] = 1.5

In [50]:
#14
total_visits = df['visits'].sum()
print(total_visits)

19

In [51]:
#15
mean_ages = df.groupby('animal')['age'].mean()
print(mean_ages)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [53]:
#16
df.loc['k'] = ['dog', 5.5, 2, 'no']
print(df)
df = df.drop('k')
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  5.5       2       no
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [54]:
#17
animal_counts = df['animal'].value_counts()
print(animal_counts)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

In [55]:
#18
sorted_df = df.sort_values(by=['age', 'visits'], ascending=[False, True])
print(sorted_df)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [56]:
#19
df['priority'] = df['priority'].map({'yes': True, 'no': False})
print(df['priority'])

a     True
b     True
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: priority, dtype: bool

In [57]:
#20
df.loc[df['animal'] == 'snake', 'animal'] = 'python'
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

In [59]:
#21
df = pd.DataFrame(np.random.random(size=(5, 3)))
row_mean = df.mean(axis=1)
result = df.sub(row_mean, axis=0)
print(result)

          0         1         2
0 -0.308644  0.149691  0.158953
1  0.080109  0.207530 -0.287639
2  0.373320 -0.369903 -0.003417
3 -0.253455  0.195222  0.058233
4  0.262410 -0.180279 -0.082132