<a href="https://colab.research.google.com/github/leesungyeon-dot/10thML/blob/week_2/Week1_%EB%B3%B5%EC%8A%B5%EA%B3%BC%EC%A0%9C_%EC%9D%B4%EC%84%B1%EC%97%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"# **1주차 복습과제**\n",
        "- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.\n",
        "- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.\n",
        "  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO\n",
        "- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗"
      ],
      "metadata": {
        "id": "jkGNNJY3S65Z"
      }

In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /tmp/build-env-8744k94k/bin/python
  version: '3.12'
SIMD Extensions:
  baseline:
  - SSE
  - SSE2
  - SSE3
  found:
  - SSSE3
  - SSE41
  - POPCNT
  - SSE42
  - AVX
  - F16C
  - FMA3
  - AVX2
  not found:
  - AVX512F
  - AVX512CD
  - AVX512_KNL
  - AVX512_KNM
  - AVX512_SKX
  - AVX512_CLX
  - AVX512_CNL
  - AVX512_ICL

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [4]:
null_vector_fifth_one = np.zeros(10)
null_vector_fifth_one[4] = 1
print(null_vector_fifth_one)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

In [5]:
vector_range = np.arange(10, 50)
print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [6]:
vector_to_reverse = np.arange(10)
reversed_vector = vector_to_reverse[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]

In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [8]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [10]:
random_3x3x3_array = np.random.random((3, 3, 3))
print(random_3x3x3_array)

[[[0.39675471 0.9462284  0.45015382]
  [0.5829965  0.42713524 0.22878774]
  [0.91002876 0.38260005 0.3006866 ]]

 [[0.7342857  0.52071896 0.31075503]
  [0.31001263 0.74331865 0.73062298]
  [0.13111538 0.60179982 0.75318518]]

 [[0.89676758 0.19714124 0.1037132 ]
  [0.16220634 0.24392898 0.24797936]
  [0.42863132 0.60175266 0.91576276]]]

In [11]:
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print(min_value, max_value)

0.012478074917670168 0.9778286076485403

In [12]:
random_vector_30 = np.random.random(30)
mean_value = random_vector_30.mean()
print(mean_value)

0.498777708499334

In [13]:
border_array = np.ones((10, 10))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [14]:
existing_array = np.ones((3, 3))
print("# before\n", existing_array)

# before
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [15]:
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("\n# after\n", bordered_array[1:-1, 1:-1]) # This is if I understood the example to be just the inner part of the 5x5 matrix.

# after
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [16]:
print(0 * np.nan) # nan (Not a Number) * 0 = nan
print(np.nan == np.nan) # False, nan is never equal to nan
print(np.inf > np.nan) # False, any comparison with nan is false (except nan != nan which is true)
print(np.nan - np.nan) # nan, nan - nan = nan
print(np.nan in set([np.nan])) # True, set treats nan as equal for membership checking
print(0.3 == 3 * 0.1) # False, floating point precision issues

nan
False
False
nan
True
False

In [17]:
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - random_matrix_5x5.mean()) / random_matrix_5x5.std()
print(normalized_matrix)

[[-1.3826484  -1.46439743  0.77142111 -0.18431794  1.65341945]
 [ 0.12943094 -0.96392594  1.47103868  0.22220543 -0.63084645]
 [ 1.70742627 -0.70876378 -0.75706842  0.68908945 -1.47690248]
 [-0.24106477  0.0862713  -0.0326151  -1.20475445  1.55492554]
 [ 1.73261725 -0.10308634 -0.31879504 -0.57122545  0.02256657]]

In [18]:
matrix_5x3 = np.ones((5, 3))
matrix_3x2 = np.ones((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print(product_matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

In [19]:
print(np.array(0) / np.array(0)) # nan, Division by zero results in nan for floats
print(np.array(0) // np.array(0)) # 0, Integer division by zero can result in 0 or an error depending on NumPy version and platform. In newer numpy, it returns 0. (RuntimeWarning: divide by zero encountered in floor_divide)
print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18]), Converting nan to int results in an extremely large negative number (or a specific value depending on architecture), then back to float retains this large number, not nan.

nan
0
[-9.22337204e+18]

/tmp/ipykernel_391/1932374072.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) # nan, Division by zero results in nan for floats
/tmp/ipykernel_391/1932374072.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # 0, Integer division by zero can result in 0 or an error depending on NumPy version and platform. In newer numpy, it returns 0. (RuntimeWarning: divide by zero encountered in floor_divide)
/tmp/ipykernel_391/1932374072.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18]), Converting nan to int results in an extremely large negative number (or a specific value depending on architecture), then back to float retains this large number, not nan.

In [20]:
matrix_row_values = np.tile(np.arange(5), (5, 1))
print(matrix_row_values)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [21]:
random_vector_10 = np.random.random(10)
sorted_vector = np.sort(random_vector_10)
print(sorted_vector)

[0.09600691 0.12872098 0.2163242  0.28851612 0.48274825 0.56751905
 0.61319778 0.71573005 0.97868748 0.99994238]

In [22]:
import pandas as pd

In [23]:
print(pd.__version__)

2.2.2

In [24]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

In [25]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

None

In [26]:
display(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [27]:
display(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [28]:
display(df[['animal', 'age']])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [29]:
display(df.loc[df.index[[3, 4, 8]], ['animal', 'age']])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [30]:
display(df[df['visits'] > 3])

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [31]:
display(df[df['age'].isnull()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [32]:
display(df[(df['animal'] == 'cat') & (df['age'] < 3)])

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [33]:
display(df[df['age'].between(2, 4)])

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [34]:
df.loc['f', 'age'] = 1.5
display(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [35]:
total_visits = df['visits'].sum()
print(total_visits)

19

In [36]:
mean_age_by_animal = df.groupby('animal')['age'].mean()
display(mean_age_by_animal)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [37]:
df.loc['k'] = ['cow', 4.0, 2, 'yes']
display(df)

df = df.drop('k')
display(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cow  4.0       2      yes

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [38]:
animal_counts = df['animal'].value_counts()
display(animal_counts)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

In [39]:
df_sorted = df.sort_values(by=['age', 'visits'], ascending=[False, True])
display(df_sorted)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [40]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
display(df)

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [41]:
df['animal'] = df['animal'].replace('snake', 'python')
display(df)

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

In [42]:
df_random = pd.DataFrame(np.random.random(size=(5, 3)))
df_normalized = df_random.sub(df_random.mean(axis=1), axis=0)
display(df_normalized)

          0         1         2
0  0.182088 -0.143577 -0.038511
1  0.352495 -0.202820 -0.149676
2  0.248463 -0.530874  0.282411
3  0.039346  0.008268 -0.047613
4  0.199329  0.072565 -0.271894

## 문제 및 정답 정리

### **넘파이 문제**

### 1. Import the numpy package under the name `np`.

In [43]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [44]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /tmp/build-env-8744k94k/bin/python
  version: '3.12'
SIMD Extensions:
  baseline:
  - SSE
  - SSE2
  - SSE3
  found:
  - SSSE3
  - SSE41
  - POPCNT
  - SSE42
  - AVX
  - F16C
  - FMA3
  - AVX2
  not found:
  - AVX512F
  - AVX512CD
  - AVX512_KNL
  - AVX512_KNM
  - AVX512_SKX
  - AVX512_CLX
  - AVX512_CNL
  - AVX512_ICL

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [45]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [46]:
null_vector_fifth_one = np.zeros(10)
null_vector_fifth_one[4] = 1
print(null_vector_fifth_one)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [47]:
vector_range = np.arange(10, 50)
print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [48]:
vector_to_reverse = np.arange(10)
reversed_vector = vector_to_reverse[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [49]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [50]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [51]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [52]:
random_3x3x3_array = np.random.random((3, 3, 3))
print(random_3x3x3_array)

[[[0.02569824 0.88612848 0.6223454 ]
  [0.47917538 0.59674525 0.25084123]
  [0.86706074 0.82338207 0.00838421]]

 [[0.25296878 0.29473788 0.86461653]
  [0.70928635 0.95361392 0.54854598]
  [0.90557059 0.56191168 0.05055063]]

 [[0.23711265 0.77547236 0.97491722]
  [0.18555558 0.88204178 0.4170884 ]
  [0.981034   0.12553015 0.05420926]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [53]:
random_10x10_array = np.random.random((10, 10))
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
print(min_value, max_value)

0.001520279322368312 0.9963509397167409

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [54]:
random_vector_30 = np.random.random(30)
mean_value = random_vector_30.mean()
print(mean_value)

0.4713450943494557

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [55]:
border_array = np.ones((10, 10))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [56]:
existing_array = np.ones((3, 3))
print("# before\n", existing_array)

# before
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [57]:
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("\n# after\n", bordered_array[1:-1, 1:-1])

# after
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [58]:
print(0 * np.nan) # nan (Not a Number) * 0 = nan
print(np.nan == np.nan) # False, nan is never equal to nan
print(np.inf > np.nan) # False, any comparison with nan is false (except nan != nan which is true)
print(np.nan - np.nan) # nan, nan - nan = nan
print(np.nan in set([np.nan])) # True, set treats nan as equal for membership checking
print(0.3 == 3 * 0.1) # False, floating point precision issues

nan
False
False
nan
True
False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [59]:
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - random_matrix_5x5.mean()) / random_matrix_5x5.std()
print(normalized_matrix)

[[ 1.35789924  0.86241085  0.03063818 -1.07752801  1.01507127]
 [-1.43448626  0.75332613 -0.16807006 -1.25941147  1.72658319]
 [ 1.69591721 -0.89979197  0.10668795 -0.5257615  -0.16875589]
 [ 0.77028196 -1.16520526  1.50856698 -0.19637197  0.39808171]
 [-0.47692564  0.47010199 -1.3440076  -0.56544433 -1.41380671]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [60]:
matrix_5x3 = np.ones((5, 3))
matrix_3x2 = np.ones((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print(product_matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [61]:
print(np.array(0) / np.array(0)) # nan, Division by zero results in nan for floats
print(np.array(0) // np.array(0)) # 0, Integer division by zero can result in 0 or an error depending on NumPy version and platform. In newer numpy, it returns 0. (RuntimeWarning: divide by zero encountered in floor_divide)
print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18]), Converting nan to int results in an extremely large negative number (or a specific value depending on architecture), then back to float retains this large number, not nan.

nan
0
[-9.22337204e+18]

/tmp/ipykernel_391/1932374072.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) # nan, Division by zero results in nan for floats
/tmp/ipykernel_391/1932374072.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # 0, Integer division by zero can result in 0 or an error depending on NumPy version and platform. In newer numpy, it returns 0. (RuntimeWarning: divide by zero encountered in floor_divide)
/tmp/ipykernel_391/1932374072.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18]), Converting nan to int results in an extremely large negative number (or a specific value depending on architecture), then back to float retains this large number, not nan.

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [62]:
matrix_row_values = np.tile(np.arange(5), (5, 1))
print(matrix_row_values)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [63]:
random_vector_10 = np.random.random(10)
sorted_vector = np.sort(random_vector_10)
print(sorted_vector)

[0.09331184 0.24303998 0.43954767 0.54923216 0.61980923 0.78498239
 0.82162075 0.82747333 0.88396771 0.88998634]

## **판다스 문제**

### 1. Import pandas under the alias `pd`.

In [64]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [65]:
print(pd.__version__)

2.2.2

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [66]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.

In [67]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

None

### 5. Display a summary of the basic statistics about data of this DataFrame.

In [68]:
display(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [69]:
display(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [70]:
display(df[['animal', 'age']])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [71]:
display(df.loc[df.index[[3, 4, 8]], ['animal', 'age']])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [72]:
display(df[df['visits'] > 3])

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [73]:
display(df[df['age'].isnull()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [74]:
display(df[(df['animal'] == 'cat') & (df['age'] < 3)])

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [75]:
display(df[df['age'].between(2, 4)])

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [76]:
df.loc['f', 'age'] = 1.5
display(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [77]:
total_visits = df['visits'].sum()
print(total_visits)

19

### 15. Calculate the mean age for each different animal in `df`.

In [78]:
mean_age_by_animal = df.groupby('animal')['age'].mean()
display(mean_age_by_animal)

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [79]:
df.loc['k'] = ['cow', 4.0, 2, 'yes']
display(df)

df = df.drop('k')
display(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cow  4.0       2      yes

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [80]:
animal_counts = df['animal'].value_counts()
display(animal_counts)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal\t| age\t|visits|\tpriority
---|---|---|---|---
i|\tdog|\t7.0|\t2|\tno
e|\tdog|\t5.0|\t2|\tno
g|\tsnake|\t4.5|\t1|\tno
j|\tdog|\t3.0|\t1|\tno
b|\tcat|\t3.0|\t3|\tyes
a|\tcat|\t2.5|\t1|\tyes
f|\tcat|\t1.5|\t3|\tno
c|\tsnake|\t0.5|\t2|\tno
h|\tcat|\tNaN|\t1|\tyes
d|\tdog|\tNaN|\t3|\tyes

In [81]:
df_sorted = df.sort_values(by=['age', 'visits'], ascending=[False, True])
display(df_sorted)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.
(hint: `map`)

In [82]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
display(df)

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [83]:
df['animal'] = df['animal'].replace('snake', 'python')
display(df)

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [84]:
df_random = pd.DataFrame(np.random.random(size=(5, 3)))
df_normalized = df_random.sub(df_random.mean(axis=1), axis=0)
display(df_normalized)

          0         1         2
0 -0.222348  0.577448 -0.355100
1  0.022456  0.039153 -0.061609
2  0.599551 -0.272769 -0.326782
3 -0.055387  0.404017 -0.348630
4 -0.140475 -0.156854  0.297330