# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [42]:
print(np.__version__)
print(np.show_config)

2.0.2
<function show at 0x000001D18C50B550>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

In [4]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [5]:
array1=np.zeros(10)
array1[4]=1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [8]:
array2=np.arange(10,50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [9]:
array3=np.arange(10)
print(array3[::-1])

[9 8 7 6 5 4 3 2 1 0]

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [10]:
array4=np.arange(9)
array5=array4.reshape(3,3)
print(array5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [11]:
array6=np.array([1,2,0,0,4,0])
print(np.nonzero(array6))

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [13]:
array7=np.random.rand(3,3,3)
print(array7)

[[[8.97737646e-01 6.36541634e-01 4.17914804e-01]
  [5.07846818e-01 1.86004307e-01 9.30071098e-01]
  [9.37707271e-01 5.38910359e-01 7.46021037e-01]]

 [[7.70487027e-01 3.22329848e-01 5.28196624e-02]
  [1.07432440e-01 2.65467642e-04 8.45054931e-02]
  [4.72206679e-01 8.81255537e-01 3.77683651e-01]]

 [[8.43491042e-01 5.51083552e-01 9.82765914e-01]
  [9.04589119e-01 7.25662202e-01 7.97965078e-01]
  [2.09892100e-01 6.94268877e-03 2.06248332e-01]]]

### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [14]:
array8=np.random.rand(10,10)
print(np.min(array8), np.max(array8))

0.007066218178700234 0.9893213107734072

### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [16]:
array9=np.random.rand(30)
print(np.mean(array9))

0.5045116652350253

### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [18]:
array10=np.ones((10,10))
array10[1:-1,1:-1]=0
print(array10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [20]:
array11=np.ones((5,5))
print(array11)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [21]:
array11[0,:]=0
array11[-1,:]=0
array11[:,0]=0
array11[:,-1]=0
print(array11)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [33]:
print(0 * np.nan)
# 결측값이 계산 과정에서 사라지는 것을 방지하기 위해, 연산에 NaN이 포함되면 결과도 NaN으로 유지된다.

print(np.nan == np.nan)
# NaN은 '알 수 없는 값'을 의미하기 때문에 자기 자신과도 같다고 판단하지 않는다. 

print(np.inf > np.nan)
# NaN은 정의되지 않은 값이므로 어떤 값과도 크기 비교가 성립하지 않는다.

print(np.nan - np.nan)
# 연산에 NaN이 포함되면 결과도 NaN이다. 

print(np.nan in set([np.nan]))
# set 안에 같은 객체의 NaN이 존재하기 때문에 True가 반환된다.

print(0.3 == 3 * 0.1)
# 부동소수점 표현의 정밀도 문제로 0.1을 정확하게 표현할 수 없어 3*0.1의 계산 결과가 0.3과 정확히 같지 않기 때문이다.

nan
False
False
nan
True
False

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [26]:
array12=np.random.rand(5,5)
array_mean=np.mean(array12)
array_std=np.std(array12)
print((array12-array_mean)/array_std)

[[-0.98634066  0.27052906 -1.34443912 -0.50048869  1.38164931]
 [ 1.63089003 -1.06654608 -1.3330017   0.25621077 -0.44578214]
 [ 0.96282153 -1.36048912 -0.24615679  0.77840522 -1.45134156]
 [ 0.25122311 -0.32952685 -0.57696142  0.72196614 -0.90617531]
 [-0.26217674  1.94364817  1.47631516  0.36841201  0.76735566]]

### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [28]:
A=np.ones((5,3))
B=np.ones((3,2))
print(np.dot(A,B))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
print(np.array(0) / np.array(0))
# 0을 0으로 나누면 결과가 정의되지 않아서 nan이 반환된다. 

print(np.array(0) // np.array(0))
# 정수형 나눗셈에서 0//0은 nan 대신 0을 반환한다. (NumPy 특수처리) 

print(np.array([np.nan]).astype(int).astype(float))
# nan은 float 전용 개념이라 int로 변환하면 예측할 수 없는 값이 된다.

nan
0
[-9.22337204e+18]

C:\Users\youth\AppData\Local\Temp\ipykernel_28584\3027451727.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\youth\AppData\Local\Temp\ipykernel_28584\3027451727.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\youth\AppData\Local\Temp\ipykernel_28584\3027451727.py:7: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [39]:
array14=np.zeros((5,5))
for i in range(1,5):
    array14[:,i]=i
print(array14)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [36]:
array13=np.random.rand(10)
print(np.sort(array13))

[0.23346234 0.26961759 0.45361157 0.46022513 0.49488847 0.57336065
 0.64740813 0.69940953 0.8638973  0.99677225]

## **판다스**


### 1. Import pandas under the alias `pd`.

In [89]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [90]:
print(pd.__version__)

2.3.3

## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [91]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(data,index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [92]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None

### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [93]:
print(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [94]:
print(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [95]:
print(df[['animal','age']])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [96]:
print(df.iloc[[3,4,8],[0,1]])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [97]:
print(df[df['visits']>3])

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [98]:
print(df[df['age'].isnull()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [99]:
iscat=df['animal']=='cat'
age_under3=df['age']<3
print(df[iscat&age_under3])

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).

In [100]:
print(df[(2<=df['age'])&(df['age']<=4)])

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [101]:
df.loc['f','age']=1.5

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [102]:
print(df['visits'].sum())

19

### 15. Calculate the mean age for each different animal in `df`.

In [103]:
print(df.groupby('animal')['age'].mean())

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [104]:
df.loc['k']=['cat',3,2,'yes']
df.drop(index='k',inplace=True)

### 17. Count the number of each type of animal in `df`.

In [105]:
print(df['animal'].value_counts())

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [106]:
print(df.sort_values(by=['age','visits'],ascending=[False,True]))

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [107]:
df['priority']=df['priority'].map({'yes':True,'no':False})

### 20. In the 'animal' column, change the 'snake' entries to 'python'.

In [108]:
df['animal']=df['animal'].replace('snake','python')

In [109]:
# 확인용 df 출력 셀
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [115]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

df.apply(lambda x : x-x.mean(),axis=1)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278