In [1]:
# 1. Import pandas under the alias pd
import pandas as pd

In [2]:
# 2. Print the version of pandas that has been imported
print(pd.__version__)

2.2.2

In [3]:
# 문제 풀이 전 numpy 임포트
import numpy as np

# 3. Create a DataFrame df from this dictionary data which has the index labels

data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(data, index=labels)

df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [4]:
# 4. Display a summary of the basic information about this DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

In [5]:
# 5. Display a summary of the basic statistics about data of this DataFrame
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [6]:
# 6. Return the first 3 rows
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [7]:
# 7. Select just the 'animal' and 'age' columns
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [8]:
# 8. Select rows [3,4,8] and columns ['animal','age']
df.loc[df.index[[3,4,8]], ['animal','age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [9]:
# 9. Select rows where visits > 3
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [10]:
# 10. Select rows where age is NaN
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [11]:
# 11. animal == cat AND age < 3
df[(df['animal']=='cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [12]:
# 12. age between 2 and 4
df[df['age'].between(2,4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [13]:
# 13. Change age in row 'f' to 1.5
df.loc['f','age'] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [14]:
# 14. sum of visits
df['visits'].sum()

np.int64(19)

In [15]:
# 15. mean age for each animal
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [16]:
# 16. append row 'k' then delete it

df.loc['k'] = ['dog', 4, 1, 'yes']
print("After adding row k")
print(df)

df = df.drop('k')
print("\nAfter deleting row k")
print(df)

After adding row k
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  4.0       1      yes

After deleting row k
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [17]:
# 17. count each animal
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

In [18]:
# 18. Sort by age(desc), visits(asc)

df_sorted = df.sort_values(by=['age','visits'], ascending=[False, True])
df_sorted

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [19]:
# 19. replace yes/no with boolean

df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [20]:
# 20. change snake to python

df['animal'] = df['animal'].replace('snake','python')
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

In [21]:
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

In [22]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
print("original df")
print(df)

# subtract row mean
df_sub = df.sub(df.mean(axis=1), axis=0)

print("\nrow mean subtracted")
print(df_sub)

original df
          0         1         2
0  0.135488  0.887852  0.932606
1  0.445568  0.388236  0.257596
2  0.657368  0.492617  0.964238
3  0.800984  0.455205  0.801058
4  0.041718  0.769458  0.003171

row mean subtracted
          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278